openapi: 3.0.2
info:
  title: Ad-service API
  version: "1.0"
servers:
  - url: http://localhost:5000/api/v1
paths:
  /ad:
    get:
      parameters:
        - name: offset
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: limit
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: age
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: integer
        - name: gender
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: country
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: platform
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/adResponse"
                x-content-type: application/json
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ad"
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
components:
  schemas:
    conditions:
      type: object
      properties:
        ageStart:
          type: integer
        ageEnd:
          type: integer
        male:
          type: boolean
        female:
          type: boolean
        country:
          type: array
          items:
            type: string
        platform:
          type: array
          items:
            type: string
    ad:
      required:
        - endAt
        - startAt
        - title
      type: object
      properties:
        title:
          type: string
        startAt:
          type: string
          format: date-time
        endAt:
          type: string
          format: date-time
        conditions:
          $ref: "#/components/schemas/conditions"
    adResponse:
      required:
        - endAt
        - title
      type: object
      properties:
        title:
          type: string
        endAt:
          type: string
          format: date-time
      example:
        endAt: 2000-01-23T04:56:07.000+00:00
        title: title
