/*
 * Ad-service API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Conditions struct {
	AgeStart int32 `json:"ageStart,omitempty"`

	AgeEnd int32 `json:"ageEnd,omitempty"`

	Country []string `json:"country,omitempty"`

	Platform []string `json:"platform,omitempty"`
}
