/*
 * Ad-service API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type AdResponse struct {
	Title string `db:"title" json:"title"`

	EndAt time.Time `db:"end_at" json:"endAt"`
}
