/*
 * Ad-service API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type Ad struct {
	Title string `db:"title" json:"title" binding:"required"`

	StartAt time.Time `db:"start_at" json:"startAt" binding:"required"`

	EndAt time.Time `db:"end_at" json:"endAt" binding:"required"`

	Conditions *Conditions `json:"conditions,omitempty"`
}
