/*
 * Ad-service API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type Ad struct {
	Title string `db:"title" json:"title"`

	StartAt time.Time `db:"start_At" json:"startAt"`

	EndAt time.Time `db:"end_at" json:"endAt"`

	Conditions *Conditions `db:"condition" json:"conditions,omitempty"`
}
