/*
 * Ad-service API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type Ad struct {
	Title string `json:"title"`

	StartAt time.Time `json:"startAt"`

	EndAt time.Time `json:"endAt"`

	Conditions *Conditions `json:"conditions,omitempty"`
}
